2012/04/19 12:49:29 [error] [exception.CDbException] SQLSTATE[42000] [1049] Unknown database 'blog'
2012/04/19 12:49:30 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection.' in D:\inetpub\htdocs\test-task\yii\framework\db\CDbConnection.php:388
Stack trace:
#0 D:\inetpub\htdocs\test-task\yii\framework\db\CDbConnection.php(331): CDbConnection->open()
#1 D:\inetpub\htdocs\test-task\yii\framework\db\CDbConnection.php(309): CDbConnection->setActive(true)
#2 D:\inetpub\htdocs\test-task\yii\framework\base\CModule.php(388): CDbConnection->init()
#3 D:\inetpub\htdocs\test-task\yii\framework\base\CApplication.php(431): CModule->getComponent('db')
#4 D:\inetpub\htdocs\test-task\yii\framework\db\ar\CActiveRecord.php(615): CApplication->getDb()
#5 D:\inetpub\htdocs\test-task\yii\framework\db\ar\CActiveRecord.php(2263): CActiveRecord->getDbConnection()
#6 D:\inetpub\htdocs\test-task\yii\framework\db\ar\CActiveRecord.php(379): CActiveRecordMetaData->__construct(Object(Post))
#7 D:\inetpub\htdocs\test-task\yii\framework\web\CActiveDataProvider.php(75): CActiveRecord::model('Post')
#8 D:\inetpub\htdocs\test-task\yii\demos\blog\protected\controllers\PostController.php(132): CActiveDataProvider->__construct('Post', Array)
#9 D:\inetpub\htdocs\test-task\yii\framework\web\actions\CInlineAction.php(50): PostController->actionIndex()
#10 D:\inetpub\htdocs\test-task\yii\framework\web\CController.php(309): CInlineAction->runWithParams(Array)
#11 D:\inetpub\htdocs\test-task\yii\framework\web\filters\CFilterChain.php(134): CController->runAction(Object(CInlineAction))
#12 D:\inetpub\htdocs\test-task\yii\framework\web\filters\CFilter.php(41): CFilterChain->run()
#13 D:\inetpub\htdocs\test-task\yii\framework\web\CController.php(1146): CFilter->filter(Object(CFilterChain))
#14 D:\inetpub\htdocs\test-task\yii\framework\web\filters\CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#15 D:\inetpub\htdocs\test-task\yii\framework\web\filters\CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#16 D:\inetpub\htdocs\test-task\yii\framework\web\CController.php(292): CFilterChain->run()
#17 D:\inetpub\htdocs\test-task\yii\framework\web\CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#18 D:\inetpub\htdocs\test-task\yii\framework\web\CWebApplication.php(276): CController->run('index')
#19 D:\inetpub\htdocs\test-task\yii\framework\web\CWebApplication.php(135): CWebApplication->runController('post/index')
#20 D:\inetpub\htdocs\test-task\yii\framework\base\CApplication.php(162): CWebApplication->processRequest()
#21 D:\inetpub\htdocs\test-task\yii\demos\blog\index.php(11): CApplication->run()
#22 {main}
REQUEST_URI=/test-task/yii/demos/blog/index.php/post/index
---
2012/10/02 01:44:52 [error] [exception.CDbException] SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: NO)
2012/10/02 01:44:52 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection.' in D:\server\www\task_Anna\php\idn-test-task\framework\db\CDbConnection.php:388
Stack trace:
#0 D:\server\www\task_Anna\php\idn-test-task\framework\db\CDbConnection.php(331): CDbConnection->open()
#1 D:\server\www\task_Anna\php\idn-test-task\framework\db\CDbConnection.php(309): CDbConnection->setActive(true)
#2 D:\server\www\task_Anna\php\idn-test-task\framework\base\CModule.php(388): CDbConnection->init()
#3 D:\server\www\task_Anna\php\idn-test-task\framework\base\CApplication.php(431): CModule->getComponent('db')
#4 D:\server\www\task_Anna\php\idn-test-task\framework\db\ar\CActiveRecord.php(615): CApplication->getDb()
#5 D:\server\www\task_Anna\php\idn-test-task\framework\db\ar\CActiveRecord.php(2263): CActiveRecord->getDbConnection()
#6 D:\server\www\task_Anna\php\idn-test-task\framework\db\ar\CActiveRecord.php(379): CActiveRecordMetaData->__construct(Object(Post))
#7 D:\server\www\task_Anna\php\idn-test-task\framework\web\CActiveDataProvider.php(75): CActiveRecord::model('Post')
#8 D:\server\www\task_Anna\php\idn-test-task\demos\blog\protected\controllers\PostController.php(132): CActiveDataProvider->__construct('Post', Array)
#9 D:\server\www\task_Anna\php\idn-test-task\framework\web\actions\CInlineAction.php(50): PostController->actionIndex()
#10 D:\server\www\task_Anna\php\idn-test-task\framework\web\CController.php(309): CInlineAction->runWithParams(Array)
#11 D:\server\www\task_Anna\php\idn-test-task\framework\web\filters\CFilterChain.php(134): CController->runAction(Object(CInlineAction))
#12 D:\server\www\task_Anna\php\idn-test-task\framework\web\filters\CFilter.php(41): CFilterChain->run()
#13 D:\server\www\task_Anna\php\idn-test-task\framework\web\CController.php(1146): CFilter->filter(Object(CFilterChain))
#14 D:\server\www\task_Anna\php\idn-test-task\framework\web\filters\CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#15 D:\server\www\task_Anna\php\idn-test-task\framework\web\filters\CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#16 D:\server\www\task_Anna\php\idn-test-task\framework\web\CController.php(292): CFilterChain->run()
#17 D:\server\www\task_Anna\php\idn-test-task\framework\web\CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#18 D:\server\www\task_Anna\php\idn-test-task\framework\web\CWebApplication.php(276): CController->run('')
#19 D:\server\www\task_Anna\php\idn-test-task\framework\web\CWebApplication.php(135): CWebApplication->runController('')
#20 D:\server\www\task_Anna\php\idn-test-task\framework\base\CApplication.php(162): CWebApplication->processRequest()
#21 D:\server\www\task_Anna\php\idn-test-task\demos\blog\index.php(11): CApplication->run()
#22 {main}
REQUEST_URI=/task_Anna/php/idn-test-task/demos/blog/
---
2012/10/02 01:54:50 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "user".' in D:\server\www\task_Anna\php\idn-test-task\framework\web\CWebApplication.php:280
Stack trace:
#0 D:\server\www\task_Anna\php\idn-test-task\framework\web\CWebApplication.php(135): CWebApplication->runController('user')
#1 D:\server\www\task_Anna\php\idn-test-task\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 D:\server\www\task_Anna\php\idn-test-task\demos\blog\index.php(11): CApplication->run()
#3 {main}
REQUEST_URI=/task_Anna/php/idn-test-task/demos/blog/index.php/user
---
2012/10/02 01:57:02 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "user".' in D:\server\www\task_Anna\php\idn-test-task\framework\web\CWebApplication.php:280
Stack trace:
#0 D:\server\www\task_Anna\php\idn-test-task\framework\web\CWebApplication.php(135): CWebApplication->runController('user')
#1 D:\server\www\task_Anna\php\idn-test-task\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 D:\server\www\task_Anna\php\idn-test-task\demos\blog\index.php(11): CApplication->run()
#3 {main}
REQUEST_URI=/task_Anna/php/idn-test-task/demos/blog/index.php/user
---
2012/10/02 01:57:11 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "user/admin".' in D:\server\www\task_Anna\php\idn-test-task\framework\web\CWebApplication.php:280
Stack trace:
#0 D:\server\www\task_Anna\php\idn-test-task\framework\web\CWebApplication.php(135): CWebApplication->runController('user/admin')
#1 D:\server\www\task_Anna\php\idn-test-task\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 D:\server\www\task_Anna\php\idn-test-task\demos\blog\index.php(11): CApplication->run()
#3 {main}
REQUEST_URI=/task_Anna/php/idn-test-task/demos/blog/index.php/user/admin
---
